In [3]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([1,2,3])
x=(a+b)
print(x.shape)

(2, 3)


In [6]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a[a>3])
a[3:]=0
print(a)

[4 5 6]
[1 2 3 0 0 0]


In [10]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
mask=np.array([True,False,True])
result=a[mask]
print(result)

[[1 2]
 [5 6]]


In [12]:
import numpy as np
a=np.random.randint(0,99,(2,3))
b=np.random.randint(0,99,(3,))
result=a+b
print("Shape of Result\n",result.shape)

Shape of Result
 (2, 3)


In [14]:
import numpy as np
x=np.arange(10)
x[x%2==0]*=2
print(x)

[ 0  1  4  3  8  5 12  7 16  9]


In [18]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a[(a>2)&(a<6)])

[3 4 5]


In [17]:
import numpy as np
a=np.array([1,2,3,4,])
print(a[a>2])

[3 4]


In [21]:
import numpy as np
a=np.arange(50).reshape(10,5)
selected_rows=a[a[:,0]>20]
print(a[:,0]>20)

[False False False False False  True  True  True  True  True]


In [24]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,0,1],[0,1,0]],dtype=bool)
result=a[b]
print(result)

[1 3 5]


In [25]:
import numpy as np
a=np.array([10,20,30,0,50])
mask=np.array([True,False,True,False,True])
result=a[mask]
print(result)

[10 30 50]


In [27]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
x=a[:,[False,True]]
print(x)

[[2]
 [4]
 [6]]


In [29]:
import numpy as np
a=np.random.randint(0,99,(2,3))
b=np.random.randint(0,99,(3,))
print(a)
print(b)
result=a*b
print("Result\n",result)

[[33 63 49]
 [ 8 15  5]]
[11 10 63]
Result
 [[ 363  630 3087]
 [  88  150  315]]


In [30]:
import numpy as np
a=np.array([1,2,3,4.5,6])
mask=np.array([True,False,True,False,True])
result=a[mask]*10
print(result)


[10. 30. 60.]


In [32]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([10,20,30])
x=a+b
print(x)

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [37]:
import numpy as np
a=np.random.uniform(0,1,(5,))
print(a)
print(a[a>0.5])

[0.0920925  0.31835549 0.33332195 0.66888708 0.2647813 ]
[0.66888708]


In [38]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9,0]])
mask=np.array([True,False,True])
print(arr[mask])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [40]:
import numpy as np
a=np.array([[1,2],[3,4],[4,7]])
print(a[a[:,1]%2==0])

[[1 2]
 [3 4]]


In [43]:
import numpy as np
a=np.array([[1,2],[3,4],[4,7]])
print(a[a[:,0]%2==0,1])

[7]


In [44]:
import numpy as np
a=np.array([[1,2],[3,4],[4,7]])
print(a[a%2==0])

[2 4 4]


In [46]:
import numpy as np
a=np.array([[1,2],[3,4],[4,7]])
print(a[:,a[1,:]%2==0][:,0])

[2 4 7]


In [48]:
import numpy as np
a=np.array([1,2,3])
x=2*a
print(x)

[2 4 6]


In [50]:
import numpy as np
x=np.array([1,2,3,4,5])
mask=(x%2==0)
print(mask)

[False  True False  True False]


In [51]:
import numpy as np
a=np.array([10,20,30,40,50])
idx=np.array([4,0,4,1])
print(a[idx])

[50 10 50 20]


In [56]:
import numpy as np
a=np.array([10,20,30,40,50])
mask=a>25

idx=np.array([2,3])

print(a[mask])
print(a[idx])

[30 40 50]
[30 40]
