In [2]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[6,7]])
A@B

array([[17, 20],
       [39, 46]])

In [4]:
import numpy as np
A=np.array([[1,2],[3,4]])
transposed=A.T
transposed=np.transpose(A)
print(transposed)

[[1 3]
 [2 4]]


In [7]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
result=A*B
print(result)

[[ 5 12]
 [21 32]]


In [15]:
import numpy as np
A=np.array([[1,2],[3,4]])
det=np.linalg.det(A)
print(det)

-2.0000000000000004


In [17]:
import numpy as np
A=np.array([[1,2],[3,4]])
inverse=np.linalg.inv(A)
print(inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [20]:
import numpy as np
A=np.array([[1,2],[3,4]])
rank=np.linalg.matrix_rank(A)
print(rank)

2


In [21]:
import numpy as np
A=np.array([[1,2],[3,4]])
eginvalues,eginvectors=np.linalg.eig(A)
print(eginvalues)
print(eginvectors)


[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [23]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
solve=np.linalg.solve(A,B)
print(solve)


[[-3. -4.]
 [ 4.  5.]]


In [28]:
import numpy as np

A = np.random.randint(1, 100, size=(5, 5))
B = np.random.randint(1, 100, size=(5, 5))

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

dotpro = A @ B
print("\n Dot Product:\n", dotpro)

Trans = A.T
print("\n Transpose of A :\n", Trans)

multi = A * B
print("\n Multiplication (A * B):\n", multi)

det_A = np.linalg.det(A)
print("\n Determinant of A :", det_A)

if det_A != 0:
    A_inv = np.linalg.inv(A)
    print("\n Inverse of A \n", A_inv)
else:
    print("\n Inverse of A: Determinant is zero, inverse does not exist.")

rank_A = np.linalg.matrix_rank(A)
print("\n Rank of A :", rank_A)




Matrix A:
 [[ 5 89 24 42 96]
 [57  9 36 13 15]
 [26 44 66 43 12]
 [14 67 17 73 72]
 [56 60  2 22 45]]

Matrix B:
 [[43 95 16 77 13]
 [24 36 61 23  7]
 [58 27 17 87 50]
 [ 2 92  1 20 21]
 [15 11 72 83  8]]

 Dot Product:
 [[ 5267  9247 12871 13328  3538]
 [ 5006  8072  3166  9233  2997]
 [ 6268  9924  5129 10612  4945]
 [ 4422 11709  9857 11534  3610]
 [ 4683 10053  7852 10041  2070]]

 Transpose of A :
 [[ 5 57 26 14 56]
 [89  9 44 67 60]
 [24 36 66 17  2]
 [42 13 43 73 22]
 [96 15 12 72 45]]

 Multiplication (A * B):
 [[ 215 8455  384 3234 1248]
 [1368  324 2196  299  105]
 [1508 1188 1122 3741  600]
 [  28 6164   17 1460 1512]
 [ 840  660  144 1826  360]]

 Determinant of A : 575054621.9999999

 Inverse of A 
 [[-0.00657973  0.01016779 -0.00378609  0.00133632  0.00951901]
 [ 0.00077019 -0.02452683  0.01539757 -0.01134863  0.02058433]
 [ 0.0099781   0.0099756   0.0087323  -0.00877149 -0.01290604]
 [-0.01621138 -0.00212319  0.00105278  0.02362334 -0.00278607]
 [ 0.01464329  0.02064384 

In [40]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\n Eigenvalues of A :\n", eigenvalues)
print("\nEigenvectors of A :\n", eigenvectors)



 Eigenvalues of A :
 [194.81198526+0.j         -65.11858222+0.j
  44.93097498+9.17490105j  44.93097498-9.17490105j
 -21.55535301+0.j        ]

Eigenvectors of A :
 [[-0.52297914+0.j         -0.75197541+0.j         -0.09744978-0.06270091j
  -0.09744978+0.06270091j  0.0721923 +0.j        ]
 [-0.31306869+0.j          0.58771219+0.j          0.26044322-0.09065169j
   0.26044322+0.09065169j -0.74927798+0.j        ]
 [-0.42747936+0.j          0.03086783+0.j          0.71451889+0.j
   0.71451889-0.j          0.26572192+0.j        ]
 [-0.53109532+0.j         -0.27325435+0.j         -0.49071623+0.30704008j
  -0.49071623-0.30704008j  0.01395866+0.j        ]
 [-0.40457383+0.j          0.11621791+0.j         -0.2399355 -0.08568212j
  -0.2399355 +0.08568212j  0.60213603+0.j        ]]
