In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
arr=np.array(42)
print(arr)

42


In [3]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6,]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [6]:
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6,]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [14]:
import numpy as np
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print('number of dimensions:',arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimensions: 5


In [24]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [23]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[2] + arr[3])

7


In [29]:
import numpy as np
arr=np.array([1,2,3,4,5])

arr_2d=np.array([[1,2,3],[4,5,6]])

zeros=np.zeros((3,4))
ones=np.ones((1,2))
range_arr=np.arange(0,10,2)
linspace=np.linspace(0,1,5)

identify=np.eye(3)
random_arr=np.random.rand(3,4)
print(zeros)
print("\n")
print(ones)
print("\n")
print(range_arr)
print("\n")
print(linspace)
print("\n")
print(identify)
print("\n")
print(random_arr)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1.]]


[0 2 4 6 8]


[0.   0.25 0.5  0.75 1.  ]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[0.68281759 0.62047358 0.44058274 0.75841786]
 [0.61019273 0.72611366 0.2762988  0.43768676]
 [0.22382973 0.01611343 0.47777355 0.53824443]]


In [42]:
import numpy as np
a=(1,2,3,4,5,6)
c=np.array(a)
print(c)

[1 2 3 4 5 6]


In [44]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [45]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.dtype)

int64


In [46]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.size)

6


In [47]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.ndim)

2


In [48]:
import numpy as np
arr=np.sum([[1,2,3],[4,5,6]])
print(arr)

21


In [52]:
import numpy as np
a=([[1,2,3],[4,5,6]])
arr=np.mean(a,axis=0)
arr_1=np.mean(a,axis=1)
print(arr,arr_1)


[2.5 3.5 4.5] [2. 5.]


In [53]:
import numpy as np
a=([[1,2,3],[4,5,6]])
arr=np.max(a)
arr_1=np.min(a)
print(arr,arr_1)

6 1


In [55]:
import numpy as np
b=np.array([10,40,30])
np.argmax(b)

np.int64(1)

In [58]:
import numpy as np
crop_yield=np.array([
    [10,10.2,11,12,12.3],
    [12,11.2,16.5,12,12.3],
    [13,15.2,11.8,12,12.3],
    [14,14.2,19,12,12.3]
])

print("Crop Yield Array (tons:)\n",crop_yield)
print(f'\nShape:{crop_yield.shape}')
print(f'Data Type:{crop_yield.dtype}')
print(f'Total elements:{crop_yield.size}')
print(f'Number of Dimensions"{crop_yield.ndim}')

total_yield=np.sum(crop_yield)
avg_yield_per_farm=np.mean(crop_yield,axis=1)
avg_yield_season=np.mean(crop_yield,axis=0)
max_yield=np.max(crop_yield)
min_yield=np.min(crop_yield)

print(total_yield)
print(avg_yield_per_farm)
print(avg_yield_season)
print(max_yield)
print(min_yield)

Crop Yield Array (tons:)
 [[10.  10.2 11.  12.  12.3]
 [12.  11.2 16.5 12.  12.3]
 [13.  15.2 11.8 12.  12.3]
 [14.  14.2 19.  12.  12.3]]

Shape:(4, 5)
Data Type:float64
Total elements:20
Number of Dimensions"2
255.3
[11.1  12.8  12.86 14.3 ]
[12.25  12.7   14.575 12.    12.3  ]
19.0
10.0
