In [ ]:
import numpy as np
arr=np.array([3,5,60,8,3,1,2,6,7,7,9,4,10])
print(arr)
np.sort(arr)

[ 3  5 60  8  3  1  2  6  7  7  9  4 10]


array([ 1,  2,  3,  3,  4,  5,  6,  7,  7,  8,  9, 10, 60])

In [ ]:
np.sort(arr)

array([ 1,  2,  3,  3,  4,  5,  6,  7,  7,  8,  9, 10, 60])

In [ ]:
import numpy as np
A=([3,1,2,70,11,33,5])
x=np.array(A)
print(np.sort(A))
np.argsort(x)

[ 1  2  3  5 11 33 70]


array([1, 2, 0, 6, 4, 5, 3])

In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6],[6,7]])
np.concatenate((x, y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 6, 7]])

In [42]:
a = np.arange(18)
print(a)
b = a.reshape(6,3)
print(b)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [33]:
data = np.array([1, 2, 3])

print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


In [34]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])
print("\n")
five_up = (a >= 5)
print(a[five_up])
print("\n")
divisible_by_2 = a[a%2==0]
print(divisible_by_2)
print("\n")
c = a[(a > 2) & (a < 11)]
print(c)
print("\n")
five_up = (a > 5) | (a == 5)
print(five_up)

[1 2 3 4]


[ 5  6  7  8  9 10 11 12]


[ 2  4  6  8 10 12]


[ 3  4  5  6  7  8  9 10]


[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [44]:
data = np.array([1.0, 2.0])
data * 1.9

array([1.9, 3.8])

In [50]:
import numpy as np
a = np.array([1.0, 2.0, 3.0])
b = 8.0
a * b

array([ 8., 16., 24.])